# Generated by Django 5.0.7 on 2024-07-29 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('entity', models.CharField(max_length=3, unique=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertypeall', models.CharField(max_length=50)),
                ('usertypedivision', models.CharField(max_length=50)),
                ('functiongroup', models.CharField(max_length=50)),
                ('requestfunction', models.CharField(max_length=50, unique=True)),
                ('requestdesc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ASNDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asnno', models.CharField(max_length=30, unique=True)),
                ('deliveryno', models.CharField(max_length=30)),
                ('asntype', models.CharField(max_length=30)),
                ('supplier', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=30)),
                ('invoiceno', models.CharField(max_length=30)),
                ('createdate', models.DateTimeField()),
                ('deliverydate', models.DateTimeField(blank=True, null=True)),
                ('grndate', models.DateTimeField(blank=True, null=True)),
                ('deliveryuser', models.CharField(max_length=30)),
                ('assignuser1', models.CharField(max_length=30)),
                ('assignuser2', models.CharField(max_length=30)),
                ('assignuser3', models.CharField(max_length=30)),
                ('totallines', models.IntegerField(default=0)),
                ('totalqty', models.IntegerField(default=0)),
                ('totalsales', models.FloatField(default=0)),
                ('linesreceived', models.IntegerField(default=0)),
                ('linesputaway', models.IntegerField(default=0)),
                ('receivedqty', models.IntegerField(default=0)),
                ('putawayqty', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=30)),
                ('createuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warelogic_app.entity')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnumber', models.CharField(max_length=50)),
                ('productcode', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('barcode', models.CharField(max_length=50)),
                ('packqty', models.IntegerField(default=1)),
                ('uoiqty', models.IntegerField(default=1)),
                ('costprice', models.FloatField(default=0)),
                ('salesprice', models.FloatField(default=0)),
                ('area', models.CharField(max_length=30)),
                ('sut', models.CharField(max_length=30)),
                ('abc', models.CharField(max_length=3)),
                ('createdeliveryqty', models.IntegerField(default=0)),
                ('inboundqty', models.IntegerField(default=0)),
                ('outboundqty', models.IntegerField(default=0)),
                ('allocatedqty', models.IntegerField(default=0)),
                ('onholdqty', models.IntegerField(default=0)),
                ('reconqty', models.IntegerField(default=0)),
                ('availqty', models.IntegerField(default=0)),
                ('sohqty', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warelogic_app.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Interim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interimtype', models.CharField(max_length=30)),
                ('parent', models.CharField(max_length=30)),
                ('qty', models.IntegerField(default=0)),
                ('route', models.CharField(max_length=30)),
                ('hu', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warelogic_app.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('productcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warelogic_app.productmaster')),
            ],
        ),
        migrations.CreateModel(
            name='BinContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binn', models.CharField(max_length=30)),
                ('binlocatoin', models.CharField(max_length=30, unique=True)),
                ('area', models.CharField(max_length=50)),
                ('sut', models.CharField(max_length=30)),
                ('abc', models.CharField(max_length=30)),
                ('putawayseq', models.IntegerField(default=0)),
                ('orderseq', models.IntegerField(default=0)),
                ('sohqty', models.IntegerField(default=0)),
                ('availqty', models.IntegerField(default=0)),
                ('ageing', models.IntegerField(default=0)),
                ('full', models.BooleanField(default=False)),
                ('allocated', models.BooleanField(default=False)),
                ('routed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warelogic_app.entity')),
                ('productcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warelogic_app.productmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ASNLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalqty', models.IntegerField(default=0)),
                ('receivedqty', models.IntegerField(default=0)),
                ('putawayqty', models.IntegerField(default=0)),
                ('shortqty', models.IntegerField(default=0)),
                ('extraqty', models.IntegerField(default=0)),
                ('damagedqty', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=30)),
                ('asnno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warelogic_app.asndelivery')),
                ('productcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warelogic_app.productmaster')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertypeall', models.CharField(max_length=50)),
                ('usertypedivision', models.CharField(max_length=50)),
                ('functiongroup', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('requestfunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warelogic_app.requestfunctions')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('machine', models.CharField(max_length=50)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warelogic_app.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
