# Generated by Django 5.0.7 on 2024-07-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warelogic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='duty',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
