# Generated by Django 5.0.7 on 2024-08-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warelogic_app', '0002_userprofile_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bincontent',
            name='hu',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bincontent',
            name='mixedbin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bincontent',
            name='productcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warelogic_app.productmaster'),
        ),
    ]
