# Generated by Django 5.0.7 on 2024-08-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warelogic_app', '0003_bincontent_hu_bincontent_mixedbin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bincontent',
            old_name='binlocatoin',
            new_name='binlocation',
        ),
    ]
